name: 'ADSK Deploy Action'
description: 'Dummy custom action that calls runs docker container with inputs'
author: 'abrahammer'
inputs: 
  service_id:
    description: 'service to deploy'
    required: true
    default: 'ACME'
  version:
    description: 'version to deploy'
    default: 'latest'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.service_id }}
    - ${{ inputs.version }}
